/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagementSys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Administrator
 */
public final class Notice extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form Staff_Home
     */
    public Notice() {
        initComponents();
        conn=database.java_db();
        User.setText(Login.Username.getText()); 
        loadNoticeData();
        date();  
    }
    String pdate=null;
    
void loadNoticeData(){
  
     String sql="select * from notice ";       
     try{
            pst=conn.prepareStatement(sql);                         
            rs=pst.executeQuery();
            while(NoticeTab.getRowCount() > 0 )
            {((DefaultTableModel)NoticeTab.getModel()).removeRow(0);
            }
            int col = rs.getMetaData().getColumnCount();
            while(rs.next())
            {
                Object [] rows = new Object[col];
                for(int i=1;i<=col;i++)
                {    rows[0]=rs.getObject("sno");  
                     rows[1]=rs.getObject("date");
                     rows[2]=rs.getObject("submitted_by");                                            
                     rows[3]=rs.getObject("last_date");
                     rows[4]=rs.getObject("subject");
                     rows[5]=rs.getObject("info");
                     break;   
            }                      
            ((DefaultTableModel)NoticeTab.getModel()).insertRow(rs.getRow( ) -1 , rows);
            }                           
            rs.close();
            pst.close();
         } catch (Exception ex) {
         } 
    }


public void date(){
    DateTimeFormatter dt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
    LocalDateTime now = LocalDateTime.now();
    pdate=(dt.format(now));
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        exit1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Sno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoticeTab = new javax.swing.JTable();
        Subject = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Info = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        LastDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 450));

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));

        exit1.setBackground(new java.awt.Color(255, 0, 0));
        exit1.setText("X");
        exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentManagementSys/icons/1 notice.png"))); // NOI18N
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });

        User.setFont(new java.awt.Font("Iskoola Pota", 0, 18)); // NOI18N
        User.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 294, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(exit1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(User, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 110));
        jPanel1.add(Sno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 90, 30));

        NoticeTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sno", "Date", "Submitted By", "Submission Date", "Subject", "Info"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        NoticeTab.getTableHeader().setReorderingAllowed(false);
        NoticeTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoticeTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(NoticeTab);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 280, 300));

        Subject.setText("Subject");
        jPanel1.add(Subject, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 270, 50));

        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 70, 30));

        Info.setColumns(20);
        Info.setRows(5);
        jScrollPane2.setViewportView(Info);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 270, 140));

        jLabel1.setText("Select Last Date");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 100, 40));

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 70, 30));

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 70, 30));
        jPanel1.add(LastDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit1MousePressed
        // TODO add your handling code here:
       
        dispose();
    }//GEN-LAST:event_exit1MousePressed
int xMouse,yMouse;
    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
       int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      
      this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
         xMouse=evt.getX();
         yMouse=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
      // TODO add your handling code here:
       
         int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
           String sql = null;           
            try {
                String val1;
                
                SimpleDateFormat sdf2=new SimpleDateFormat("dd-MM-yyyy");               
                val1 = sdf2.format(LastDate.getDate()); 
                String val2 = Subject.getText();
                String val3 = Info.getText();
                String val5 = Sno.getText();
                
                   sql ="update notice set last_date='"+val1+"',"
                        + "subject='"+val2+"',info='"+val3+"' "
                        + "where notice.sno='"+val5+"'";

                pst=conn.prepareStatement(sql);    
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");             
                    rs.close();
                    pst.close();     
                    LastDate.setDate(null);
                    Subject.setText(null);      
                    Info.setText(null);
                    Sno.setText(null);
                    loadNoticeData();
                    
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }finally {try{
                    rs.close();
                    pst.close();
            }catch(Exception e){
                }
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
         int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete Notice ?","Delete Notice",JOptionPane.YES_NO_OPTION);
        if(p==0){

            try {
                String sql ="delete from notice where sno= ? ";
                pst=conn.prepareStatement(sql);                                 
                pst.setString(1,Sno.getText());                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
                rs.close();
                pst.close();
                LastDate.setDate(null);
                Subject.setText(null);  
                Info.setText(null);
                Sno.setText(null);
                loadNoticeData();                   
            }
            catch (Exception e)  {                
            }
            }
    }//GEN-LAST:event_DeleteActionPerformed

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
        // TODO add your handling code here:
        loadNoticeData();
    }//GEN-LAST:event_jLabel2KeyPressed

    private void NoticeTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoticeTabMouseClicked
        // TODO add your handling code here:
        
         int i= NoticeTab.getSelectedRow();     
        TableModel Model=NoticeTab.getModel();
        try{
            int srow=NoticeTab.getSelectedRow();
            Date date = new SimpleDateFormat("dd-MM-yyyy").parse((String)Model.getValueAt(srow,3));
            LastDate.setDate(date);
       }
       catch(Exception e){           
       }
       Subject.setText(Model.getValueAt(i,4).toString());      
       Info.setText(Model.getValueAt(i,5).toString());
       Sno.setText(Model.getValueAt(i,0).toString());
    }//GEN-LAST:event_NoticeTabMouseClicked

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
          int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Send Notice ?","Add Notice",JOptionPane.YES_NO_OPTION);
        if(p==0){          
            try {
                String sql ="INSERT INTO  notice (date,"
                        + "last_date,subject,submitted_by,info) "
                        + "VALUES (? , ? , ? , ? , ? )";
                pst=conn.prepareStatement(sql);
                SimpleDateFormat sdf1=new SimpleDateFormat("dd-MM-yyyy");               
                Date date=new Date();
                pst.setString(1,sdf1.format(date));
                                
                SimpleDateFormat sdf2=new SimpleDateFormat("dd-MM-yyyy");               
                pst.setString(2,sdf2.format(LastDate.getDate()));
                
                pst.setString(3,Subject.getText());
                pst.setString(4,User.getText());
                pst.setString(5,Info.getText());    
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
                rs.close();
                pst.close();                   
                loadNoticeData();                   
            }
            catch (Exception e)  { }
            }
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JTextArea Info;
    private com.toedter.calendar.JDateChooser LastDate;
    private javax.swing.JTable NoticeTab;
    private javax.swing.JTextField Sno;
    private javax.swing.JTextField Subject;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Update;
    public static javax.swing.JLabel User;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
