/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentManagementSys;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Student_Add extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null,rs1=null;
PreparedStatement pst=null,pst1=null;
    /**
     * Creates new form Home
     */
    public Student_Add() {
        initComponents();
        conn=database.java_db();
        INS_USN.setText(Student.SearchUsn1.getText());             
        loadStudentdata();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        exit2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        INS_BRANCH = new javax.swing.JComboBox();
        INS_LBRANCH = new javax.swing.JLabel();
        INSERT = new javax.swing.JButton();
        INS_LNAME = new javax.swing.JLabel();
        UPDATE = new javax.swing.JButton();
        INS_LUSN = new javax.swing.JLabel();
        SURNAME = new javax.swing.JLabel();
        INS_LSEM = new javax.swing.JLabel();
        INS_SURNAME = new javax.swing.JTextField();
        INS_LPHNO = new javax.swing.JLabel();
        INS_LEMAIL = new javax.swing.JLabel();
        INS_LALTERNO = new javax.swing.JLabel();
        INS_EMAIL = new javax.swing.JTextField();
        INS_LADDRESS = new javax.swing.JLabel();
        INS_LFNAME = new javax.swing.JLabel();
        INS_LMNAME = new javax.swing.JLabel();
        INS_LDOB = new javax.swing.JLabel();
        INS_NAME = new javax.swing.JTextField();
        INS_USN = new javax.swing.JTextField();
        INS_PHNO = new javax.swing.JTextField();
        INS_ALTERNO = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        INS_ADDRESS = new javax.swing.JTextArea();
        INS_FNAME = new javax.swing.JTextField();
        INS_MNAME = new javax.swing.JTextField();
        INS_Sem = new javax.swing.JComboBox();
        INS_DATEOFBIRTH = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 450));

        jPanel9.setBackground(new java.awt.Color(0, 0, 204));

        exit2.setBackground(new java.awt.Color(255, 0, 0));
        exit2.setText("X");
        exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exit2MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/StudentManagementSys/icons/2 Student-id-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(exit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 650, 100));

        INS_BRANCH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COMPUTER SCIENCE", "CIVIL", "ELECTRONIC & COMMUNICATION", "MECHANIC" }));
        jPanel1.add(INS_BRANCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 130, -1));

        INS_LBRANCH.setText("BRANCH");
        jPanel1.add(INS_LBRANCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        INSERT.setText("INSERT");
        INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INSERTActionPerformed(evt);
            }
        });
        jPanel1.add(INSERT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        INS_LNAME.setText("Name");
        jPanel1.add(INS_LNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        UPDATE.setText("UPDATE");
        UPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATE, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));

        INS_LUSN.setText("USN");
        jPanel1.add(INS_LUSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        SURNAME.setText("SURNAME");
        jPanel1.add(SURNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        INS_LSEM.setText("SEM");
        jPanel1.add(INS_LSEM, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, -1));

        INS_SURNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INS_SURNAMEActionPerformed(evt);
            }
        });
        jPanel1.add(INS_SURNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 100, -1));

        INS_LPHNO.setText("PHONE NO");
        jPanel1.add(INS_LPHNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        INS_LEMAIL.setText("EMAIL ID");
        jPanel1.add(INS_LEMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        INS_LALTERNO.setText("ALTERNATIVE NO");
        jPanel1.add(INS_LALTERNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));
        jPanel1.add(INS_EMAIL, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, -1));

        INS_LADDRESS.setText("ADDRESS");
        jPanel1.add(INS_LADDRESS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        INS_LFNAME.setText("FATHER NAME");
        jPanel1.add(INS_LFNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        INS_LMNAME.setText("MOTHER NAME");
        jPanel1.add(INS_LMNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        INS_LDOB.setText("DATE OF BIRTH");
        jPanel1.add(INS_LDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));
        jPanel1.add(INS_NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, -1));
        jPanel1.add(INS_USN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 100, -1));
        jPanel1.add(INS_PHNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 110, -1));

        INS_ALTERNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INS_ALTERNOActionPerformed(evt);
            }
        });
        jPanel1.add(INS_ALTERNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 110, -1));

        INS_ADDRESS.setColumns(20);
        INS_ADDRESS.setRows(5);
        jScrollPane1.setViewportView(INS_ADDRESS);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        INS_FNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INS_FNAMEActionPerformed(evt);
            }
        });
        jPanel1.add(INS_FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 100, -1));

        INS_MNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INS_MNAMEActionPerformed(evt);
            }
        });
        jPanel1.add(INS_MNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, -1));

        INS_Sem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "IV", "V", "VI", "VII", "VII" }));
        jPanel1.add(INS_Sem, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));
        jPanel1.add(INS_DATEOFBIRTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
void loadStudentdata(){
        
     String sql="select * from student where usn = ?";       
     try{
            pst=conn.prepareStatement(sql);            
            pst.setString(1,INS_USN.getText());             
            rs=pst.executeQuery();
            if(rs.next()){
                INS_NAME.setText(rs.getString("name"));
                INS_SURNAME.setText(rs.getString("lname"));
                INS_FNAME.setText(rs.getString("fname"));
                INS_MNAME.setText(rs.getString("mname")); 
                INS_PHNO.setText(rs.getString("phone"));
                INS_ALTERNO.setText(rs.getString("alter_phno"));
                INS_EMAIL.setText(rs.getString("gmail"));
                INS_ADDRESS.setText(rs.getString("address"));
                INS_Sem.setSelectedItem(rs.getString("sem"));
            
                String branch = rs.getString("branch");
                INS_BRANCH.setSelectedItem(branch);
               
                try{
                   Date sdf = new SimpleDateFormat("yyyy-MM-dd").parse((rs.getString("dob")));
                   INS_DATEOFBIRTH.setDate(sdf);
                }
                catch(Exception e){ }  
           }
            rs.close();
            pst.close();
         } catch (Exception ex) {
         } 
 }
    private void INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INSERTActionPerformed
        // TODO add your handling code here:

        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){

            try {
                String sql ="INSERT INTO `college`.`student` (usn,name,lname,fname,"
                        + "mname,dob,sem,branch,phone,alter_phno,gmail,"
                        + "address,password) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";
                
                String sql1 ="INSERT INTO `internal` (usn,name,branch,sem) VALUES (?, ?, ?, ?)";
                pst=conn.prepareStatement(sql);
                pst1=conn.prepareStatement(sql1);
                
                pst.setString(1,INS_USN.getText());
                pst.setString(2,INS_NAME.getText());
                pst.setString(3,INS_SURNAME.getText());
                pst.setString(4,INS_FNAME.getText());                
                pst.setString(5,INS_MNAME.getText());
                
                SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");               
                pst.setString(6,sdf.format(INS_DATEOFBIRTH.getDate()));
                
                pst.setString(7,INS_Sem.getSelectedItem().toString());
                pst.setString(8,INS_BRANCH.getSelectedItem().toString());
                pst.setString(9,INS_PHNO.getText());
                pst.setString(10,INS_ALTERNO.getText());
                pst.setString(11,INS_EMAIL.getText());
                pst.setString(12,INS_ADDRESS.getText());
                 
                SimpleDateFormat psd=new SimpleDateFormat("ddMMyyyy");               
                pst.setString(13,psd.format(INS_DATEOFBIRTH.getDate()));
                
                pst1.setString(1,INS_USN.getText());
                pst1.setString(2,INS_NAME.getText());
                pst1.setString(3,INS_BRANCH.getSelectedItem().toString());
                pst1.setString(4,INS_Sem.getSelectedItem().toString());
                
                pst.executeUpdate();
                pst1.executeUpdate();
                
                pst.close();                     
                pst1.close();
                
                JOptionPane.showMessageDialog(null,"Data is saved successfully");
              
                     
                   
                    dispose();
                    
            }
            catch (Exception e)  {
                
            }
            }
    }//GEN-LAST:event_INSERTActionPerformed

    private void INS_FNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INS_FNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INS_FNAMEActionPerformed

    private void UPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEActionPerformed
        // TODO add your handling code here:
          
         int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try{
                String value1 = INS_NAME.getText();
                String value2 = INS_FNAME.getText(); 
                String value3 = INS_MNAME.getText();
                String value4 = INS_SURNAME.getText();
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String value5 = sdf.format(INS_DATEOFBIRTH.getDate());
                String value6 = INS_EMAIL.getText();
                String value7 = INS_USN.getText();
                String value8 = INS_PHNO.getText();  
                String value9 = INS_BRANCH.getSelectedItem().toString();
                String value10 = INS_Sem.getSelectedItem().toString();
                String value11 = INS_ALTERNO.getText();
                String value12 = INS_ADDRESS.getText();
                SimpleDateFormat pass= new SimpleDateFormat("ddMMyyyy");
                String value13 = pass.format(INS_DATEOFBIRTH.getDate());


                String sql= "update student set usn='"+value7+"',name='"+value1+"', lname='"+value4+"', "
                        + "dob='"+value5+"',gmail='"+value6+"',fname='"+value2+"',mname='"+value3+"',"
                        + "phone='"+value8+"',branch='"+value9+"',sem='"+value10+"',password='"+value13+"', "
                        + "alter_phno='"+value11+"',address='"+value12+"'"
                        + "where student.usn='"+value7+"'";
                
               String sql1= "update internal set usn='"+value7+"', name='"+value1+"', branch='"+value9+"', sem='"+value10+"' where internal.usn='"+value7+"'";
                
               pst=conn.prepareStatement(sql);
               pst1=conn.prepareStatement(sql1);
               pst.execute();
               pst1.execute();
                
                JOptionPane.showMessageDialog(null, "Record Updated");                
                rs.close();
                pst.close();
                dispose();
            }catch(Exception e){ } 
        }        
    }//GEN-LAST:event_UPDATEActionPerformed

    private void exit2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit2MousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit2MousePressed
int xMouse,yMouse;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
      int y = evt.getYOnScreen();
      
      this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void INS_ALTERNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INS_ALTERNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INS_ALTERNOActionPerformed

    private void INS_SURNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INS_SURNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INS_SURNAMEActionPerformed

    private void INS_MNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INS_MNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INS_MNAMEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Add().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INSERT;
    public static javax.swing.JTextArea INS_ADDRESS;
    public static javax.swing.JTextField INS_ALTERNO;
    private javax.swing.JComboBox INS_BRANCH;
    private com.toedter.calendar.JDateChooser INS_DATEOFBIRTH;
    private javax.swing.JTextField INS_EMAIL;
    public static javax.swing.JTextField INS_FNAME;
    private javax.swing.JLabel INS_LADDRESS;
    private javax.swing.JLabel INS_LALTERNO;
    private javax.swing.JLabel INS_LBRANCH;
    private javax.swing.JLabel INS_LDOB;
    private javax.swing.JLabel INS_LEMAIL;
    private javax.swing.JLabel INS_LFNAME;
    private javax.swing.JLabel INS_LMNAME;
    private javax.swing.JLabel INS_LNAME;
    private javax.swing.JLabel INS_LPHNO;
    private javax.swing.JLabel INS_LSEM;
    private javax.swing.JLabel INS_LUSN;
    public static javax.swing.JTextField INS_MNAME;
    public static javax.swing.JTextField INS_NAME;
    public static javax.swing.JTextField INS_PHNO;
    private javax.swing.JTextField INS_SURNAME;
    private javax.swing.JComboBox INS_Sem;
    public static javax.swing.JTextField INS_USN;
    private javax.swing.JLabel SURNAME;
    private javax.swing.JButton UPDATE;
    private javax.swing.JButton exit2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
